import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readExecution, root, scheduleExecution } from './execution.mjs';
import { witnessEvidence, writeWitnessEvidence } from './replay/witnesses/evidence.mjs';
import { checkWitnesses, readWitnessRegistry, witnessProfiles } from './replay/witnesses/index.mjs';

// Language-neutral witness completion. Any port runs this over the generated
// corpus instead of TypeScript's test suite: it evaluates the shared
// classifiers, requires every registered witness and declared action, and
// writes the evidence consumed by Go (and any other port) under
// .formal-traces/go-parity-witnesses. Failing profiles write nothing and
// remove stale evidence so a later consumer cannot reuse an older pass.
//
// Every run also prints the fragility report (which required labels few or no
// sampled histories reach, and how diverse the sampled histories are) and,
// when formal/witness-baseline.json records the pinned corpus, compares each
// required label's sampled hits with that baseline. evaluate fails when a
// gated label drops below the tolerance; report only prints; baseline --write
// records the current corpus as the baseline.
const tracesPrefix = '.formal-traces/';
const commands = ['evaluate', 'report', 'baseline'];
const usage = ['Usage: node formal/witnesses.mjs evaluate [--profile <name|all>] [--traces <dir>] [--out <dir>] [--baseline <path>]',
  '       node formal/witnesses.mjs report [--profile <name|all>] [--traces <dir>] [--baseline <path>]',
  '       node formal/witnesses.mjs baseline --write [--profile <name|all>] [--traces <dir>] [--baseline <path>]'].join('\n');
export const defaultBaselinePath = 'formal/witness-baseline.json';
export const reportFileName = 'witness-report.json';
// A required label reached by this many sampled histories or fewer is rare.
export const rareMaximum = 3;
// freshSeedSigma bounds the fresh-seed gate: on a corpus other than the recorded
// one, a gated label fails only when its sampled count falls below tolerance
// AND below the recorded count minus this many Poisson standard deviations,
// never below one hit. Per-label counts of ten to forty vary by a third or
// more between seeds, so the tolerance alone would fail most fresh seeds on
// noise; the bound keeps the fresh-seed gate a collapse detector.
export const baselineDefaults = { tolerance: 0.5, gatedMinimum: 10, freshSeedSigma: 4 };

// Seeds are compared in one form only: '0x' plus lowercase hex of the unsigned
// 64-bit value, whatever form the environment, the manifest or a baseline file
// wrote them in ('0xD1A1CA', '13738442' and '0xd1a1ca' are one seed).
export function canonicalSeed(value) {
  if (typeof value !== 'string' || !/^(0x[\da-fA-F]{1,16}|\d{1,20})$/.test(value) || BigInt(value) > 0xffffffffffffffffn) {
    throw new Error(`Seed must be an unsigned 64-bit integer; got ${JSON.stringify(value)}`);
  }
  return `0x${BigInt(value).toString(16)}`;
}

// The corpus under evaluation was generated by run-models.mjs with QUINT_SEED
// or the manifest seed; the evaluator resolves the same value the same way.
export function resolveCorpusSeed(environment = process.env, execution = readExecution()) {
  return canonicalSeed(environment.QUINT_SEED || execution.settings.seed);
}

// The recorded baseline belongs to the manifest seed: a baseline written under
// another seed would make the pinned lane look like exploration. Evaluation,
// reporting and a partial rewrite refuse such a file; only the full rewrite,
// which replaces it, may run, so the recovery the error names is possible.
export function staleBaselineProblem(baseline, manifestSeed, { command, profile }) {
  if (baseline === undefined || baseline.seed === manifestSeed) return undefined;
  if (command === 'baseline' && profile === 'all') return undefined;
  return `recorded at seed ${baseline.seed} but the manifest seed is ${manifestSeed}; rewrite it with baseline --write --profile all under the manifest seed`;
}

// Which gate rule judges a corpus. A byte-identical sampled corpus cannot come
// from another seed, so an equal fingerprint always keeps the strict tolerance
// rule; only a corpus that differs AND was generated under another seed is an
// exploration corpus judged by the collapse rule.
export function gateRule(seed, baseline, sameCorpus) {
  if (baseline === undefined || seed === undefined || seed === null) return { rule: 'tolerance', sameSeed: null, contradiction: false };
  const sameSeed = canonicalSeed(seed) === canonicalSeed(baseline.seed);
  if (sameCorpus === true) return { rule: 'tolerance', sameSeed, contradiction: !sameSeed };
  return { rule: sameSeed ? 'tolerance' : 'collapse', sameSeed, contradiction: false };
}

export function parseArguments(args) {
  const [command, ...rest] = args;
  if (!commands.includes(command)) throw new Error(usage);
  const options = { command, profile: 'all', traces: '.formal-traces', out: '.formal-traces/go-parity-witnesses', baseline: defaultBaselinePath, write: false };
  for (let index = 0; index < rest.length; index += 1) {
    const argument = rest[index];
    if (argument === '--write' && command === 'baseline') { options.write = true; continue; }
    const key = typeof argument === 'string' && argument.startsWith('--') ? argument.slice(2) : undefined, value = rest[index + 1];
    if (!['profile', 'traces', 'out', 'baseline'].includes(key) || value === undefined || (key === 'out' && command !== 'evaluate')) throw new Error(usage);
    options[key] = value;
    index += 1;
  }
  if (command === 'baseline' && !options.write) throw new Error(usage);
  return options;
}

// Sampled histories come from the profile's generate.outputDirectory; exported
// public-action regressions from .formal-traces/regressions/<profile>. Both
// are relocated under --traces so an alternate corpus can be evaluated. The
// directory a history came from decides its kind in the evidence.
export function traceKind(path, directories) {
  const directory = dirname(resolve(path));
  if (directory === resolve(directories.sampled)) return 'sampled';
  if (directory === resolve(directories.regressions)) return 'regression';
  throw new Error(`${path}: outside the sampled and regression corpus directories`);
}

// `execution` is the scheduled manifest (scheduleExecution): the exported
// regressions it names complete the profile's corpus.
export function witnessCorpus(profile, tracesRoot, execution = scheduleExecution(), directory = root) {
  const model = execution.models.find(candidate => candidate.profile === profile);
  if (model === undefined) throw new Error(`${profile}: no scheduled model in formal/execution.json`);
  const output = model.generate?.outputDirectory;
  if (typeof output !== 'string' || !output.startsWith(tracesPrefix)) throw new Error(`${profile}: unsupported generate.outputDirectory`);
  const base = resolve(directory, tracesRoot);
  const directories = { sampled: resolve(base, output.slice(tracesPrefix.length)), regressions: resolve(base, 'regressions', profile) };
  if (!existsSync(directories.sampled)) throw new Error(`${profile}: missing sampled histories in ${directories.sampled}; run node formal/run-models.mjs generate first`);
  const paths = readdirSync(directories.sampled).filter(name => name.endsWith('.itf.json')).sort().map(name => resolve(directories.sampled, name));
  for (const regression of model.replayRegressions ?? []) paths.push(resolve(directories.regressions, `${regression}.itf.json`));
  const missing = paths.filter(path => !existsSync(path));
  if (missing.length) throw new Error(`${profile}: missing histories ${missing.map(path => relative(directory, path)).join(', ')}`);
  const kinds = new Map(paths.map(path => [basename(path), traceKind(path, directories)]));
  if (kinds.size !== paths.length) throw new Error(`${profile}: a sampled history and a regression share a file name`);
  return { paths, kinds, directories };
}

export function witnessCorpusPaths(profile, tracesRoot, execution = scheduleExecution(), directory = root) {
  return witnessCorpus(profile, tracesRoot, execution, directory).paths;
}

export function selectedProfiles(selection, execution = readExecution()) {
  const scheduled = execution.models.map(model => model.profile).filter(profile => witnessProfiles.includes(profile));
  if (selection === 'all') return scheduled;
  if (!scheduled.includes(selection)) throw new Error(`Unknown witness profile ${selection}; expected one of ${scheduled.join(', ')} or all`);
  return [selection];
}

// The baseline records, per profile and required label, how many sampled
// histories of the pinned corpus reached the label, with the seed and a
// fingerprint of that sampled corpus.
export function readBaseline(path) {
  if (!existsSync(path)) return undefined;
  const baseline = JSON.parse(readFileSync(path, 'utf8'));
  if (baseline?.schemaVersion !== 1 || typeof baseline.seed !== 'string' || !(baseline.tolerance > 0 && baseline.tolerance < 1)
    || !Number.isInteger(baseline.gatedMinimum) || baseline.gatedMinimum < 1 || !(baseline.freshSeedSigma > 0)
    || typeof baseline.profiles !== 'object' || baseline.profiles === null) {
    throw new Error(`${path}: unsupported witness baseline`);
  }
  baseline.seed = canonicalSeed(baseline.seed);
  return baseline;
}

// The fingerprint covers the sampled histories' content (their vars and
// states). Quint stamps every ITF file's #meta with its creation time, so the
// byte-level corpus digests in the evidence differ on each regeneration of the
// pinned seed although the histories are identical; this digest does not.
export function sampledCorpusFingerprint(corpus) {
  const sampled = corpus.paths.filter(path => corpus.kinds.get(basename(path)) === 'sampled')
    .map(path => ({ name: basename(path), path })).sort((a, b) => a.name.localeCompare(b.name, 'en'));
  const digest = createHash('sha256');
  for (const { name, path } of sampled) {
    const content = JSON.parse(readFileSync(path, 'utf8'));
    delete content['#meta'];
    digest.update(`${name} ${createHash('sha256').update(JSON.stringify(content)).digest('hex')}\n`);
  }
  return digest.digest('hex');
}

export function recordBaseline(existing, entries, recordedSeed, defaults = baselineDefaults) {
  const seed = canonicalSeed(recordedSeed);
  if (existing !== undefined && canonicalSeed(existing.seed) !== seed) {
    throw new Error(`Recorded baseline seed ${existing.seed} differs from ${seed}; rewrite every profile with --profile all`);
  }
  const baseline = existing ?? { schemaVersion: 1, seed, ...defaults, profiles: {} };
  for (const { profile, evidence, fingerprint } of entries) {
    baseline.profiles[profile] = { sampledHistories: evidence.diversity.sampledHistories, corpusSha256: fingerprint,
      labels: Object.fromEntries(evidence.required.map(label => [label, evidence.labels[label]?.sampled ?? 0])) };
  }
  baseline.profiles = Object.fromEntries(Object.entries(baseline.profiles).sort(([a], [b]) => a.localeCompare(b, 'en')));
  return baseline;
}

// The gate: a required label whose recorded sampled count is at least
// gatedMinimum fails when the fresh sampled count drops below tolerance times
// the recorded count. Which rule applies is decided by the generation seed,
// never by the corpus fingerprint: under the recorded seed a changed count is
// exact evidence of a model or classifier change and the tolerance rule holds,
// whatever the fingerprint says. Under another seed (exploration) the count
// must also fall more than freshSeedSigma Poisson standard deviations below
// the recorded one, and at least to below one hit, so seed noise on small
// counts does not fail the lane while a collapsed label still does. Labels
// recorded below the minimum, or not recorded, are reported and never gated.
export function baselineFindings(profile, rows, baseline, { freshCorpus = false } = {}) {
  const recorded = baseline?.profiles[profile];
  const findings = { recorded: recorded !== undefined, gated: [], failed: [], ungated: [], unrecorded: [], rule: freshCorpus ? 'collapse' : 'tolerance' };
  for (const { label, sampled } of rows) {
    const base = recorded?.labels[label];
    if (base === undefined) { findings.unrecorded.push(label); continue; }
    if (base < baseline.gatedMinimum) { findings.ungated.push(label); continue; }
    findings.gated.push(label);
    const tolerance = base * baseline.tolerance;
    const minimum = freshCorpus ? Math.max(1, Math.min(tolerance, base - baseline.freshSeedSigma * Math.sqrt(base))) : tolerance;
    if (sampled < minimum) findings.failed.push({ label, baseline: base, sampled, minimum, rule: findings.rule });
  }
  return findings;
}

export function profileReport(profile, evidence, missing, fingerprint, baseline, { seed } = {}) {
  const rows = evidence.required.map(label => ({ label, sampled: evidence.labels[label]?.sampled ?? 0, regression: evidence.labels[label]?.regression ?? 0 }));
  const recorded = baseline?.profiles[profile];
  const decision = gateRule(seed, baseline, recorded === undefined ? null : recorded.corpusSha256 === fingerprint);
  return { profile, histories: evidence.traces, diversity: evidence.diversity, missing,
    fragile: rows.filter(row => row.sampled <= rareMaximum && row.regression === 0),
    rare: rows.filter(row => row.sampled <= rareMaximum && row.regression >= 1),
    sameCorpusAsBaseline: recorded === undefined ? null : recorded.corpusSha256 === fingerprint,
    seed: seed === undefined ? null : canonicalSeed(seed), sameSeedAsBaseline: decision.sameSeed, seedContradiction: decision.contradiction,
    baseline: baselineFindings(profile, rows, baseline, { freshCorpus: decision.rule === 'collapse' }) };
}

const percent = value => `${Math.round(value * 100)}%`;
const hits = row => `${row.label} (${row.sampled} sampled, ${row.regression} regression)`;

export function formatReport(report) {
  const lines = [];
  for (const summary of Object.values(report.profiles)) {
    const { diversity, baseline } = summary;
    lines.push(`witness/${summary.profile}: ${diversity.sampledHistories} sampled + ${summary.histories - diversity.sampledHistories} regression histories;`
      + ` ${diversity.distinctActionSequences} distinct action sequences, ${diversity.distinctObservationSequences} distinct observation sequences (sampled)`);
    if (summary.missing.length) lines.push(`  missing: ${summary.missing.join(', ')}`);
    lines.push(`  fragile, unpinned (sampled <= ${rareMaximum}, no regression): ${summary.fragile.length ? summary.fragile.map(hits).join(', ') : 'none'}`);
    lines.push(`  pinned but rare (sampled <= ${rareMaximum}, regression >= 1): ${summary.rare.length ? summary.rare.map(hits).join(', ') : 'none'}`);
    if (!baseline.recorded) { lines.push('  baseline: none recorded for this profile'); continue; }
    const rule = summary.baseline.rule === 'collapse'
      ? `exploration seed ${summary.seed}: gated at ${percent(report.baseline.tolerance)} and ${report.baseline.freshSeedSigma} sigma below the recorded count`
      : summary.seedContradiction ? `recorded corpus although the seed reads ${summary.seed}; judged strictly: gated at ${percent(report.baseline.tolerance)}`
      : summary.sameSeedAsBaseline === null ? `seed unknown, judged strictly: gated at ${percent(report.baseline.tolerance)}`
      : summary.sameCorpusAsBaseline ? `recorded seed and corpus: gated at ${percent(report.baseline.tolerance)}`
      : `recorded seed, corpus differs (a model or classifier change; rewrite the baseline deliberately): gated at ${percent(report.baseline.tolerance)}`;
    lines.push(`  baseline ${report.baseline.seed} (${rule}): ${baseline.gated.length} labels gated,`
      + ` ${baseline.ungated.length} below the gated minimum of ${report.baseline.gatedMinimum}, ${baseline.unrecorded.length} unrecorded`);
    for (const failure of baseline.failed) lines.push(`  FAILED ${failure.label}: ${failure.sampled} sampled, minimum ${Math.round(failure.minimum * 10) / 10} (baseline ${failure.baseline}, ${failure.rule} rule)`);
  }
  return lines.join('\n');
}

export function evaluateProfiles(options, { directory = root, log = message => console.log(message), environment = process.env } = {}) {
  const execution = scheduleExecution();
  const registry = readWitnessRegistry(resolve(directory, 'formal/coverage-witnesses.json'));
  const outputDirectory = resolve(directory, options.out);
  const baselinePath = resolve(directory, options.baseline);
  const baseline = readBaseline(baselinePath);
  const seed = resolveCorpusSeed(environment, execution);
  const manifestSeed = canonicalSeed(execution.settings.seed);
  const stale = staleBaselineProblem(baseline, manifestSeed, options);
  if (stale !== undefined) throw new Error(`${options.baseline}: ${stale}`);
  const report = { schemaVersion: 1, command: options.command, traces: options.traces, seed,
    sameSeedAsBaseline: baseline === undefined ? null : seed === baseline.seed,
    baseline: baseline === undefined ? null : { path: options.baseline, seed: baseline.seed, tolerance: baseline.tolerance, gatedMinimum: baseline.gatedMinimum, freshSeedSigma: baseline.freshSeedSigma },
    profiles: {}, incomplete: [], failed: [] };
  const entries = [];
  for (const profile of selectedProfiles(options.profile, execution)) {
    const corpus = witnessCorpus(profile, options.traces, execution, directory);
    const check = checkWitnesses(profile, corpus.paths, registry);
    const evidence = witnessEvidence(profile, check, corpus, directory);
    const fingerprint = sampledCorpusFingerprint(corpus);
    const summary = profileReport(profile, evidence, check.missing, fingerprint, baseline, { seed });
    report.profiles[profile] = summary;
    entries.push({ profile, evidence, fingerprint });
    if (check.missing.length) {
      if (options.command === 'evaluate') rmSync(resolve(outputDirectory, `${profile}.json`), { force: true });
      report.incomplete.push(`witness/${profile}: ${check.traces} histories reached ${check.seen.size} labels; missing ${check.missing.join(', ')}`);
    } else if (options.command === 'evaluate') {
      const written = writeWitnessEvidence(outputDirectory, evidence);
      log(`witness/${profile}: ${check.traces} histories, ${check.seen.size} labels, ${check.required.length} required -> ${relative(directory, written)}`);
    }
    for (const failure of summary.baseline.failed) {
      report.failed.push(`witness/${profile}: ${failure.label} reached by ${failure.sampled} sampled histories, minimum ${Math.round(failure.minimum * 10) / 10} (baseline ${failure.baseline}, ${failure.rule} rule)`);
    }
  }
  if (options.command === 'baseline') {
    if (report.incomplete.length) throw new Error(`A baseline needs complete witness coverage:\n${report.incomplete.join('\n')}`);
    if (seed !== manifestSeed) throw new Error(`A baseline is recorded under the manifest seed ${manifestSeed}, not ${seed}; unset QUINT_SEED`);
    const written = recordBaseline(options.profile === 'all' ? undefined : baseline, entries, seed);
    mkdirSync(dirname(baselinePath), { recursive: true });
    writeFileSync(baselinePath, JSON.stringify(written, null, 2) + '\n');
    log(`Recorded sampled witness counts for ${entries.length} profile(s) at seed ${seed} -> ${relative(directory, baselinePath)}`);
    return report;
  }
  log(formatReport(report));
  const reportPath = resolve(directory, options.traces, reportFileName);
  mkdirSync(dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, JSON.stringify(report, null, 2) + '\n');
  if (options.command === 'evaluate') {
    const problems = [];
    if (report.incomplete.length) problems.push(`Incomplete witness coverage:\n${report.incomplete.join('\n')}`);
    if (report.failed.length) {
      problems.push(`Sampled witness hits fell below ${percent(baseline.tolerance)} of ${options.baseline} (seed ${baseline.seed}):\n${report.failed.join('\n')}`);
    }
    if (problems.length) throw new Error(problems.join('\n'));
  }
  return report;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try { evaluateProfiles(parseArguments(process.argv.slice(2))); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
