"""Exercise the release boundary using real Git commits and a fake registry."""

import hashlib
import io
import json
import os
from pathlib import Path
import stat
import subprocess
import tempfile
import tomllib
import unittest
from unittest.mock import patch
import urllib.error

import release


NEXT_VERSION = "0.24.0"
PATHS = ("typescript/package.json", "rust/Cargo.toml", "rust/Cargo.lock")
WORKSPACE_FILES = {
    "package.json": (
        '{\n  "name": "dialcache-workspace",\n  "private": true,\n'
        '  "scripts": {"build": "pnpm --dir typescript build"}\n}\n'
    ),
    "pnpm-workspace.yaml": "packages:\n  - typescript\n",
}


def version_files(npm="0.23.4", rust="0.1.0", lock=None):
    """A first Rust release may begin with a different npm version.

    Unrelated versions deliberately equal package versions so a broad text
    replacement or lockfile regeneration cannot silently pass these checks.
    """
    if lock is None:
        lock = rust
    return {
        "typescript/package.json": (
            '{\n  "name": "dialcache",\n'
            f'  "version": "{npm}",\n'
            '  "description": "Keep 0.23.4 in this text.",\n'
            '  "dependencies": {"fixture": "0.23.4"}\n}\n'
        ),
        "rust/Cargo.toml": (
            '# Keep this comment and table ordering.\n'
            '[package]\nname = "dialcache"\n'
            f'version = "{rust}"\n'
            'edition = "2021"\n\n'
            '[dependencies]\nfixture = "0.1.0"\n\n'
            '[package.metadata.fixture]\nversion = "0.1.0"\n'
        ),
        "rust/Cargo.lock": (
            '# This file is automatically @generated by Cargo.\nversion = 4\n\n'
            '[[package]]\nname = "fixture"\nversion = "0.1.0"\n'
            'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
            f'checksum = "{"a" * 64}"\n\n'
            '[[package]]\nname = "dialcache"\n'
            f'version = "{lock}"\n'
            'dependencies = [\n "fixture",\n]\n\n'
            '[[package]]\nname = "dialcache"\nversion = "0.1.0"\n'
            'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
            f'checksum = "{"b" * 64}"\n'
        ),
    }


def write_files(root, contents):
    for name, content in contents.items():
        path = root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content.encode("utf-8"))


class VersionUpdateTests(unittest.TestCase):
    def test_one_selected_version_preserves_all_other_content(self):
        before = version_files()
        expected = version_files(npm=NEXT_VERSION, rust=NEXT_VERSION)
        actual = release.versioned_files(before, NEXT_VERSION)
        self.assertEqual(actual, expected)
        self.assertEqual(before, version_files(), "Planning must not mutate its input")

        # Explicitly retain the registry copy of a same-named crate and every
        # unrelated dependency, including their checksums and ordering.
        before_lock = tomllib.loads(before["rust/Cargo.lock"])["package"]
        after_lock = tomllib.loads(actual["rust/Cargo.lock"])["package"]
        self.assertEqual(before_lock[0], after_lock[0])
        self.assertEqual(before_lock[2], after_lock[2])

    def test_update_writes_only_the_expected_version_bytes(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_files(root, version_files())
            (root / "README.md").write_bytes(b"Keep this file unchanged.\n")
            release.update_versions(root, NEXT_VERSION)
            expected = version_files(npm=NEXT_VERSION, rust=NEXT_VERSION)
            for name, text in expected.items():
                self.assertEqual((root / name).read_bytes(), text.encode("utf-8"))
            self.assertEqual((root / "README.md").read_bytes(), b"Keep this file unchanged.\n")

    def test_update_leaves_private_workspace_manifests_untouched(self):
        # The workspace root intentionally has no release version. Its presence
        # must neither redirect the release update nor add a version field.
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_files(root, {**version_files(), **WORKSPACE_FILES})
            release.update_versions(root, NEXT_VERSION)
            for name, text in WORKSPACE_FILES.items():
                self.assertEqual((root / name).read_bytes(), text.encode("utf-8"))
            expected = version_files(npm=NEXT_VERSION, rust=NEXT_VERSION)
            for name, text in expected.items():
                self.assertEqual((root / name).read_bytes(), text.encode("utf-8"))

    def test_manifest_lock_mismatch_is_rejected_before_any_file_is_written(self):
        before = version_files(lock="0.2.0")
        with self.assertRaises(ValueError):
            release.versioned_files(before, NEXT_VERSION)
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_files(root, before)
            with self.assertRaises(ValueError):
                release.update_versions(root, NEXT_VERSION)
            for name, text in before.items():
                self.assertEqual((root / name).read_bytes(), text.encode("utf-8"))

    def test_update_cannot_silently_normalize_existing_line_endings(self):
        before = {name: text.replace("\n", "\r\n") for name, text in version_files().items()}
        expected = {
            name: text.replace("\n", "\r\n")
            for name, text in version_files(npm=NEXT_VERSION, rust=NEXT_VERSION).items()
        }
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_files(root, before)
            try:
                release.update_versions(root, NEXT_VERSION)
            except ValueError:
                # Supporting only the repository's canonical formatting is
                # fine; rejecting it must leave all files untouched.
                expected = before
            for name, text in expected.items():
                self.assertEqual((root / name).read_bytes(), text.encode("utf-8"))

    def test_invalid_or_nonstable_release_versions_are_rejected(self):
        for version in ("", "v0.24.0", "0.24", "0.24.0-rc.1", "0.24.0+build", "01.2.3", "1.02.3", "1.2.03", "1.2.3\n", "-1.2.3"):
            with self.subTest(version=version), self.assertRaises(ValueError):
                release.versioned_files(version_files(), version)

    def test_unrelated_package_names_cannot_be_prepared_as_dialcache(self):
        for name in ("typescript/package.json", "rust/Cargo.toml"):
            with self.subTest(path=name):
                contents = version_files()
                contents[name] = contents[name].replace('"dialcache"', '"another-crate"', 1)
                with self.assertRaises(ValueError):
                    release.versioned_files(contents, NEXT_VERSION)


class VersionCommitTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.root = Path(self.directory.name)
        self.git("init", "--quiet")
        self.git("config", "user.name", "Release fixture")
        self.git("config", "user.email", "release-fixture@example.invalid")
        self.git("config", "commit.gpgsign", "false")
        self.git("config", "core.hooksPath", os.devnull)
        self.git("config", "core.autocrlf", "false")
        self.git("config", "core.filemode", "true")
        write_files(self.root, {**version_files(), **WORKSPACE_FILES})
        (self.root / "README.md").write_text("An existing non-version file.\n")
        self.base = self.commit()

    def git(self, *args):
        result = subprocess.run(
            ["git", *args], cwd=self.root, check=True, text=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            env={**os.environ, "GIT_CONFIG_GLOBAL": os.devnull, "GIT_CONFIG_NOSYSTEM": "1"},
        )
        return result.stdout.strip()

    def commit(self):
        self.git("add", "--all")
        self.git("commit", "--quiet", "-m", "release fixture")
        return self.git("rev-parse", "HEAD")

    def candidate(self, version=NEXT_VERSION):
        # Construct the expected candidate independently of the updater: a
        # shared updater/verifier bug must not manufacture its own evidence.
        write_files(self.root, version_files(npm=version, rust=version))

    def assert_rejected(self, version=NEXT_VERSION):
        head = self.commit()
        with self.assertRaises(ValueError):
            release.verify_version_commit(self.root, version, self.base, head)

    def test_accepts_exact_version_commit_and_unchanged_dependency_lock(self):
        self.candidate()
        head = self.commit()
        release.verify_version_commit(self.root, NEXT_VERSION, self.base, head)

    def test_verifies_selected_git_objects_instead_of_the_working_tree(self):
        self.candidate()
        head = self.commit()
        (self.root / "typescript/package.json").write_text("uncommitted unrelated work")
        release.verify_version_commit(self.root, NEXT_VERSION, self.base, head)

    def test_rejects_wrong_version_in_each_release_file(self):
        for name in PATHS:
            with self.subTest(path=name):
                self.git("reset", "--hard", self.base)
                self.candidate()
                path = self.root / name
                path.write_text(path.read_text().replace(NEXT_VERSION, "0.24.1"))
                self.assert_rejected()

    def test_rejects_stale_or_decreasing_versions(self):
        for version in ("0.23.4", "0.23.3", "0.22.99"):
            with self.subTest(version=version):
                self.git("reset", "--hard", self.base)
                self.candidate(version)
                self.assert_rejected(version)

    def test_version_comparison_is_numeric(self):
        self.candidate("0.100.0")
        head = self.commit()
        release.verify_version_commit(self.root, "0.100.0", self.base, head)

    def test_rejects_a_file_missing_from_the_version_update(self):
        self.candidate()
        (self.root / "rust/Cargo.lock").write_text(version_files()["rust/Cargo.lock"])
        self.assert_rejected()

    def test_rejects_an_extra_changed_file(self):
        self.candidate()
        (self.root / "README.md").write_text("A hidden documentation change.\n")
        self.assert_rejected()

    def test_rejects_workspace_manifest_changes_in_a_release_commit(self):
        mutations = {
            "package.json": WORKSPACE_FILES["package.json"].replace(
                '"private": true,', f'"private": true,\n  "version": "{NEXT_VERSION}",'
            ),
            "pnpm-workspace.yaml": WORKSPACE_FILES["pnpm-workspace.yaml"] + "  - surprise\n",
        }
        for name, text in mutations.items():
            with self.subTest(path=name):
                self.git("reset", "--hard", self.base)
                self.candidate()
                (self.root / name).write_text(text)
                self.assert_rejected()

    def test_rejects_an_extra_added_file(self):
        self.candidate()
        (self.root / "surprise.txt").write_text("A hidden new file.\n")
        self.assert_rejected()

    def test_rejects_an_extra_deleted_file(self):
        self.candidate()
        (self.root / "README.md").unlink()
        self.assert_rejected()

    def test_rejects_other_content_changes_in_allowed_files(self):
        mutations = {
            "typescript/package.json": ('"fixture": "0.23.4"', '"fixture": "0.23.5"'),
            "rust/Cargo.toml": ('fixture = "0.1.0"', 'fixture = "0.2.0"'),
            "rust/Cargo.lock": ('checksum = "' + "a" * 64 + '"', 'checksum = "' + "c" * 64 + '"'),
        }
        for name, (old, new) in mutations.items():
            with self.subTest(path=name):
                self.git("reset", "--hard", self.base)
                self.candidate()
                path = self.root / name
                path.write_text(path.read_text().replace(old, new))
                self.assert_rejected()

    def test_rejects_formatting_changes_even_when_parsed_values_match(self):
        self.candidate()
        path = self.root / "typescript/package.json"
        package = json.loads(path.read_text())
        path.write_text(json.dumps(package, indent=4) + "\n")
        self.assert_rejected()

    def test_rejects_line_ending_changes_in_each_release_file(self):
        for name in PATHS:
            with self.subTest(path=name):
                self.git("reset", "--hard", self.base)
                self.candidate()
                path = self.root / name
                path.write_bytes(path.read_bytes().replace(b"\n", b"\r\n"))
                self.assert_rejected()

    def test_rejects_file_mode_changes_in_each_release_file(self):
        for name in PATHS:
            with self.subTest(path=name):
                self.git("reset", "--hard", self.base)
                self.candidate()
                path = self.root / name
                path.chmod(path.stat().st_mode | stat.S_IXUSR)
                self.assert_rejected()


class PublishedCrateTests(unittest.TestCase):
    def setUp(self):
        self.directory = tempfile.TemporaryDirectory()
        self.addCleanup(self.directory.cleanup)
        self.archive = Path(self.directory.name) / "dialcache.crate"
        self.archive.write_bytes(b"Exact packaged crate bytes for the selected release.\x00\xff")
        self.checksum = hashlib.sha256(self.archive.read_bytes()).hexdigest()

    def entry(self, **changes):
        value = {"name": "dialcache", "vers": NEXT_VERSION, "cksum": self.checksum, "yanked": False}
        value.update(changes)
        return json.dumps(value)

    def test_only_the_requested_version_and_exact_archive_can_be_reused(self):
        index = "\n".join((self.entry(vers="0.23.4", cksum="0" * 64, yanked=True), self.entry(), ""))
        self.assertTrue(release.published_crate_matches(index, NEXT_VERSION, self.archive))

    def test_missing_crate_or_version_means_publication_is_still_needed(self):
        for index in ("", "\n", self.entry(vers="0.23.4")):
            with self.subTest(index=index):
                self.assertFalse(release.published_crate_matches(index, NEXT_VERSION, self.archive))

    def test_existing_version_with_different_archive_is_a_conflict(self):
        with self.assertRaises(ValueError):
            release.published_crate_matches(self.entry(cksum="0" * 64), NEXT_VERSION, self.archive)

    def test_matching_checksum_cannot_authorize_a_yanked_version(self):
        with self.assertRaises(ValueError):
            release.published_crate_matches(self.entry(yanked=True), NEXT_VERSION, self.archive)

    def test_wrong_crate_name_and_duplicate_versions_are_rejected(self):
        for index in (self.entry(name="another-crate"), self.entry() + "\n" + self.entry()):
            with self.subTest(index=index), self.assertRaises(ValueError):
                release.published_crate_matches(index, NEXT_VERSION, self.archive)

    def test_corrupt_index_does_not_mean_unpublished(self):
        with self.assertRaises(ValueError):
            release.published_crate_matches("not JSON", NEXT_VERSION, self.archive)

    def test_http_response_is_checked_against_local_archive(self):
        response = io.BytesIO((self.entry() + "\n").encode("utf-8"))
        with patch.object(release.urllib.request, "urlopen", return_value=response):
            self.assertTrue(release.check_published(NEXT_VERSION, self.archive))

    def test_http_success_with_a_conflict_does_not_skip_publication_safeguards(self):
        response = io.BytesIO(self.entry(cksum="0" * 64).encode("utf-8"))
        with patch.object(release.urllib.request, "urlopen", return_value=response):
            with self.assertRaises(ValueError):
                release.check_published(NEXT_VERSION, self.archive)

    def test_http_404_is_absent(self):
        error = urllib.error.HTTPError(release.CRATE_INDEX, 404, "Not found", {}, None)
        self.addCleanup(error.close)
        with patch.object(release.urllib.request, "urlopen", side_effect=error):
            self.assertFalse(release.check_published(NEXT_VERSION, self.archive))

    def test_http_server_and_auth_failures_are_not_absence(self):
        for status in (401, 403, 429, 500, 503):
            with self.subTest(status=status):
                error = urllib.error.HTTPError(release.CRATE_INDEX, status, "Unavailable", {}, None)
                self.addCleanup(error.close)
                with patch.object(release.urllib.request, "urlopen", side_effect=error):
                    with self.assertRaises(urllib.error.HTTPError) as caught:
                        release.check_published(NEXT_VERSION, self.archive)
                self.assertIs(caught.exception, error)

    def test_connection_failure_is_not_absence(self):
        error = urllib.error.URLError("connection timed out")
        with patch.object(release.urllib.request, "urlopen", side_effect=error):
            with self.assertRaises(urllib.error.URLError):
                release.check_published(NEXT_VERSION, self.archive)


if __name__ == "__main__":
    unittest.main()
