import { publicPrefixWitnesses, publicPrefixRule as rule, publicCheckpoint as check, witnessCommand as command } from "./public-prefix.mjs";

// Every label requires the public input sequence and its observable consequence.
export const deletionWitnessRules = [
  rule("delete-removes-every-reachable-store", "deleteRemovesRequestLocalAndRemoteTest",
    [command("init", 0), command("beginCall", 0), command("resolveLoader", 1), command("deleteEntry", 0), command("beginCall", 0)],
    check(2, {"calls": [1], "writes": 1}),
    check(4, {"calls": [1, 0], "loaders": 2, "reads": 2, "deletions": 1, "maintenance": ["ok"]})),
  rule("disabled-delete-removes-outer-memo", "deleteFromDisabledContextRemovesTest",
    [command("init", 0), command("beginCall", 0), command("resolveLoader", 1), command("deleteEntry", 20), command("beginCall", 0)],
    check(2, {"calls": [1], "writes": 1}),
    check(4, {"calls": [1, 0], "loaders": 2, "reads": 2})),
  rule("outside-delete-preserves-existing-request-memo", "deleteOutsideAnyScopeRemovesSharedLayersTest",
    [command("init", 0), command("beginCall", 0), command("resolveLoader", 1), command("deleteEntry", 24), command("beginCall", 0), command("beginCall", 12)],
    check(2, {"calls": [1], "writes": 1}),
    check(5, {"calls": [1, 1, 0], "loaders": 2, "reads": 2})),
  rule("local-only-delete-removes-local", "deleteWithoutRemoteRemovesLocalTest",
    [command("init", 4), command("beginCall", 12), command("resolveLoader", 1), command("deleteEntry", 24), command("beginCall", 12)],
    check(2, {"calls": [1], "loaders": 1}),
    check(4, {"calls": [1, 0], "loaders": 2, "deletions": 0, "maintenance": ["ok"]})),
  rule("unsupported-delete-preserves-every-store", "deleteUnsupportedRemoteChangesNothingTest",
    [command("init", 6), command("beginCall", 0), command("resolveLoader", 1), command("deleteEntry", 0), command("beginCall", 0), command("policy", 3), command("beginCall", 12), command("policy", 2), command("beginCall", 12)],
    check(3, {"deletions": 0, "maintenance": ["unsupported"]}),
    check(6, {"calls": [1, 1, 1], "loaders": 1}),
    check(8, {"calls": [1, 1, 1, 1], "loaders": 1})),
  rule("failed-delete-preserves-every-store", "remoteDeleteFailureKeepsLocalTest",
    [command("init", 0), command("beginCall", 0), command("resolveLoader", 1), command("remoteFault", 1), command("deleteEntry", 0), command("beginCall", 0), command("policy", 3), command("beginCall", 12), command("policy", 2), command("beginCall", 12)],
    check(4, {"deletions": 1, "maintenance": ["mutation_error"]}),
    check(7, {"calls": [1, 1, 1], "loaders": 1}),
    check(9, {"calls": [1, 1, 1, 1], "loaders": 1})),
  rule("delete-preserves-watermark-and-sibling-local-value", "deletePreservesWatermarkAndSiblingVariantsTest",
    [command("init", 1), command("seed", 0), command("seed", 3), command("beginCall", 0), command("beginCall", 1), command("invalidate", 0), command("deleteEntry", 0), command("beginCall", 1), command("policy", 2), command("beginCall", 13)],
    check(4, {"calls": [1, 2], "loaders": 0}),
    check(9, {"calls": [1, 2, 2, 0], "loaders": 1, "invalidations": 1, "deletions": 1})),
  rule("delete-preserves-other-instance-local-value", "deleteOneInstanceLeavesOtherInstanceTest",
    [command("init", 0), command("seed", 0), command("beginCall", 12), command("beginCall", 16), command("deleteEntry", 24), command("beginCall", 16), command("beginCall", 12)],
    check(5, {"calls": [1, 1, 1], "loaders": 0}),
    check(6, {"calls": [1, 1, 1, 0], "loaders": 1})),
  rule("late-fill-remains-shared-and-repopulates", "lateFillAfterDeleteRepopulatesTest",
    [command("init", 0), command("beginCall", 12), command("deleteEntry", 24), command("beginCall", 12), command("resolveLoader", 2), command("beginCall", 12)],
    check(3, {"calls": [0, 0], "loaders": 1}),
    check(5, {"calls": [2, 2, 2], "loaders": 1, "writes": 1})),
  rule("acquired-snapshot-completes-after-delete", "acquiredReadAfterDeleteStillReturnsTest",
    [command("init", 0), command("holdDecoding", -1), command("seed", 0), command("beginCall", 0), command("deleteEntry", 0), command("releaseLoad", 0), command("beginCall", 0)],
    check(3, {"calls": [0], "loads": 1, "loaders": 0}),
    check(5, {"calls": [1], "loaders": 0, "deletions": 1}),
    check(6, {"calls": [1, 1], "reads": 1})),
  rule("absent-delete-succeeds-without-policy", "deleteAbsentKeyReportsOkTest",
    [command("init", 0), command("deleteEntry", 24), command("beginCall", 12)],
    check(1, {"maintenance": ["ok"], "deletions": 1, "policyCalls": 0}),
    check(2, {"calls": [0], "loaders": 1})),
  rule("deleted-key-reloads-and-memoizes-new-value", "deleteThenReadMissesAndReloadsTest",
    [command("init", 0), command("beginCall", 0), command("resolveLoader", 1), command("deleteEntry", 0), command("beginCall", 0), command("resolveLoader", 4), command("beginCall", 0)],
    check(2, {"calls": [1], "loaders": 1, "writes": 1}),
    check(4, {"calls": [1, 0], "loaders": 2}),
    check(6, {"calls": [1, 2, 2], "loaders": 2, "writes": 2})),
  rule("delete-preserves-sibling-and-other-request", "deletePreservesSiblingAndOtherRequestTest",
    [command("init", 0), command("seed", 0), command("seed", 3), command("beginCall", 0), command("beginCall", 1), command("beginCall", 4), command("deleteEntry", 0), command("policy", 3), command("beginCall", 13), command("beginCall", 4), command("policy", 2), command("beginCall", 13)],
    check(5, {"calls": [1, 2, 1], "loaders": 0}),
    check(9, {"calls": [1, 2, 1, 2, 1], "loaders": 0}),
    check(11, {"calls": [1, 2, 1, 2, 1, 2], "reads": 3})),
  rule("absent-local-only-delete-succeeds", "deleteAbsentLocalOnlyReportsOkTest",
    [command("init", 4), command("deleteEntry", 24)],
    check(1, {"maintenance": ["ok"], "deletions": 0, "policyCalls": 0})),
];

export function deletionWitnesses(histories, recorder) {
  return publicPrefixWitnesses(histories, deletionWitnessRules, recorder);
}
